### ISSUE TITLE
Upgrade Win32-network to build with ghc-9.6

### ISSUE THREAD

**Issue by erikd** [input-output-hk/Win32-network#21]
* [x] Make it build (nothing required)
* [x] Make sure it builds in CI
* [ ] Upload to CHaP

**Comment by erikd** [comment]
Waiting for write access to the repo.

**Comment by erikd** [comment]
Already builds. When I get write access to the repo I will submit a PR to build it in CI.

**Comment by angerman** [comment]
@erikd you should have write access now.

**Comment by coot** [comment]
Your PR only only modified GHA, e.g. no code changes were needed for `Win32-network` to support the latest and greatest GHC.  I don't think we need to publish a new version to `CHaP`.

**Comment by erikd** [comment]
Complete.
